server:
  port: 8081

spring:
  application:
    name: healthconnect-patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthconnect_db
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
        enabled: true
# Aseg√∫rate de que estas rutas coincidan con lo que inyectas con @Value
app:
  security:
    encryption-key: 'q8V5l7LikedWep@1{3[&Cc<XD)+7_3X['
  storage:
    service:
      url: "http://localhost:8082/api/v1/storage"
      api-key: "fe40c9bd81ade2fde81e3504794f1815"
      api-secret: "8204666ebb943974633a2b6a4d925c4e21709bb56bb32bfb371fcbc69257c09a"
      bucket-name: "patient-docs-local-cipher"